/** @format */

export const jwtConstants = {
  secret: '',
};

export const DB = {
  SEQUELIZE: 'SEQUELIZE',
  DATA_SOURCE: 'DATA_SOURCE',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
  PRODUCT_REPOSITORY: 'PRODUCT_REPOSITORY',
  CART_REPOSITORY: 'CART_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
};
